template: Hello, %s!
defaultName: Stranger

metrics:
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      prefix: infra

server:
  applicationContextPath: /application
  adminContextPath: /admin
  applicationConnectors:
      - type: http
        port: 8100



